// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2HM_am1LWgADBgairKqRzqqKEFA8ORVM',
    appId: '1:19231371655:web:5c7223330f31196bbf6322',
    messagingSenderId: '19231371655',
    projectId: 'my-soulmate-app',
    authDomain: 'my-soulmate-app.firebaseapp.com',
    storageBucket: 'my-soulmate-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAseud7oWioF5Kc1Ta2Ez8eKjOCmxpIULU',
    appId: '1:19231371655:android:8c5539eb1eeec761bf6322',
    messagingSenderId: '19231371655',
    projectId: 'my-soulmate-app',
    storageBucket: 'my-soulmate-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA0wBli9WJLZ_tdHsdXV0WSyRsB2BBMDw',
    appId: '1:19231371655:ios:4151608326d5471fbf6322',
    messagingSenderId: '19231371655',
    projectId: 'my-soulmate-app',
    storageBucket: 'my-soulmate-app.firebasestorage.app',
    iosBundleId: 'com.soulmate.soulmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA0wBli9WJLZ_tdHsdXV0WSyRsB2BBMDw',
    appId: '1:19231371655:ios:4151608326d5471fbf6322',
    messagingSenderId: '19231371655',
    projectId: 'my-soulmate-app',
    storageBucket: 'my-soulmate-app.firebasestorage.app',
    iosBundleId: 'com.soulmate.soulmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2HM_am1LWgADBgairKqRzqqKEFA8ORVM',
    appId: '1:19231371655:web:6a78695b76955ba7bf6322',
    messagingSenderId: '19231371655',
    projectId: 'my-soulmate-app',
    authDomain: 'my-soulmate-app.firebaseapp.com',
    storageBucket: 'my-soulmate-app.firebasestorage.app',
  );
}
