// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSYcaP-fMHmj5zfoHJjHPYSlI0WQ_likI',
    appId: '1:822069382132:web:8d3c6dd3f71d0e8d0487a1',
    messagingSenderId: '822069382132',
    projectId: 'fir-stuff-73d8e',
    authDomain: 'fir-stuff-73d8e.firebaseapp.com',
    databaseURL: 'https://fir-stuff-73d8e.firebaseio.com',
    storageBucket: 'fir-stuff-73d8e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8Cx65cJKXyWzjjVPI4Oq-tw-vo_hO2N8',
    appId: '1:822069382132:android:caf760f2783deb830487a1',
    messagingSenderId: '822069382132',
    projectId: 'fir-stuff-73d8e',
    databaseURL: 'https://fir-stuff-73d8e.firebaseio.com',
    storageBucket: 'fir-stuff-73d8e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyIXKtpgwdxT1eDEsBb-B75sZNYr1UJhI',
    appId: '1:822069382132:ios:343260a76ecc34df0487a1',
    messagingSenderId: '822069382132',
    projectId: 'fir-stuff-73d8e',
    databaseURL: 'https://fir-stuff-73d8e.firebaseio.com',
    storageBucket: 'fir-stuff-73d8e.firebasestorage.app',
    iosBundleId: 'com.badalaryal.soulmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyIXKtpgwdxT1eDEsBb-B75sZNYr1UJhI',
    appId: '1:822069382132:ios:e1e4d4edc157fd280487a1',
    messagingSenderId: '822069382132',
    projectId: 'fir-stuff-73d8e',
    databaseURL: 'https://fir-stuff-73d8e.firebaseio.com',
    storageBucket: 'fir-stuff-73d8e.firebasestorage.app',
    iosBundleId: 'com.soulmate.soulmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSYcaP-fMHmj5zfoHJjHPYSlI0WQ_likI',
    appId: '1:822069382132:web:bd4fe7cb19000c260487a1',
    messagingSenderId: '822069382132',
    projectId: 'fir-stuff-73d8e',
    authDomain: 'fir-stuff-73d8e.firebaseapp.com',
    databaseURL: 'https://fir-stuff-73d8e.firebaseio.com',
    storageBucket: 'fir-stuff-73d8e.firebasestorage.app',
  );

}