// Mocks generated by Mockito 5.4.6 from annotations
// in soulmate/test/unit/user_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i8;

import 'package:firebase_auth/firebase_auth.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:soulmate/data/datasources/auth_service.dart' as _i5;
import 'package:soulmate/data/datasources/database_service.dart' as _i7;
import 'package:soulmate/domain/entities/chat_message.dart' as _i10;
import 'package:soulmate/domain/entities/user_model.dart' as _i4;
import 'package:soulmate/domain/repositories/user_repository.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i2.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveUser(_i4.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#saveUser, [user]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.User?> getUser(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getUser, [uid]),
            returnValue: _i3.Future<_i4.User?>.value(),
          )
          as _i3.Future<_i4.User?>);

  @override
  _i3.Future<List<_i4.User>> getUsers({
    String? gender,
    String? currentUserId,
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getUsers, [], {
              #gender: gender,
              #currentUserId: currentUserId,
              #limit: limit,
            }),
            returnValue: _i3.Future<List<_i4.User>>.value(<_i4.User>[]),
          )
          as _i3.Future<List<_i4.User>>);

  @override
  _i3.Future<void> updateUserField(String? uid, Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserField, [uid, data]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i5.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i6.User?> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i3.Stream<_i6.User?>.empty(),
          )
          as _i3.Stream<_i6.User?>);

  @override
  _i3.Future<_i6.UserCredential?> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i3.Future<_i6.UserCredential?>.value(),
          )
          as _i3.Future<_i6.UserCredential?>);

  @override
  _i3.Future<_i6.UserCredential?> signInWithApple() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithApple, []),
            returnValue: _i3.Future<_i6.UserCredential?>.value(),
          )
          as _i3.Future<_i6.UserCredential?>);

  @override
  _i3.Future<_i6.UserCredential?> signInWithEmailAndPassword(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmailAndPassword, [email, password]),
            returnValue: _i3.Future<_i6.UserCredential?>.value(),
          )
          as _i3.Future<_i6.UserCredential?>);

  @override
  _i3.Future<_i6.UserCredential?> registerWithEmailAndPassword(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#registerWithEmailAndPassword, [email, password]),
            returnValue: _i3.Future<_i6.UserCredential?>.value(),
          )
          as _i3.Future<_i6.UserCredential?>);

  @override
  _i3.Future<void> sendPasswordResetEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#sendPasswordResetEmail, [email]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateEmail(String? newEmail) =>
      (super.noSuchMethod(
            Invocation.method(#updateEmail, [newEmail]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updatePassword(String? newPassword) =>
      (super.noSuchMethod(
            Invocation.method(#updatePassword, [newPassword]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteAccount() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> confirmPasswordReset({
    required String? code,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#confirmPasswordReset, [], {
              #code: code,
              #newPassword: newPassword,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [DatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseService extends _i1.Mock implements _i7.DatabaseService {
  MockDatabaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> uploadProfileImage(String? userId, _i8.File? imageFile) =>
      (super.noSuchMethod(
            Invocation.method(#uploadProfileImage, [userId, imageFile]),
            returnValue: _i3.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#uploadProfileImage, [userId, imageFile]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<void> saveUser(_i4.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#saveUser, [user]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateUserField(String? uid, Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserField, [uid, data]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> saveFeedback(String? userId, String? message) =>
      (super.noSuchMethod(
            Invocation.method(#saveFeedback, [userId, message]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.User?> getUser(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getUser, [uid]),
            returnValue: _i3.Future<_i4.User?>.value(),
          )
          as _i3.Future<_i4.User?>);

  @override
  _i3.Future<List<_i4.User>> getUsers({
    String? gender,
    String? currentUserId,
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getUsers, [], {
              #gender: gender,
              #currentUserId: currentUserId,
              #limit: limit,
            }),
            returnValue: _i3.Future<List<_i4.User>>.value(<_i4.User>[]),
          )
          as _i3.Future<List<_i4.User>>);

  @override
  String getChatId(String? userId1, String? userId2) =>
      (super.noSuchMethod(
            Invocation.method(#getChatId, [userId1, userId2]),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.method(#getChatId, [userId1, userId2]),
            ),
          )
          as String);

  @override
  _i3.Future<List<Map<String, dynamic>>> getActiveChats(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getActiveChats, [userId]),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<void> sendMessage(String? chatId, _i10.ChatMessage? message) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [chatId, message]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateGameMessage(
    String? chatId,
    String? messageId,
    Map<String, dynamic>? gameData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateGameMessage, [
              chatId,
              messageId,
              gameData,
            ]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<Map<String, dynamic>?> getChatStream(String? chatId) =>
      (super.noSuchMethod(
            Invocation.method(#getChatStream, [chatId]),
            returnValue: _i3.Stream<Map<String, dynamic>?>.empty(),
          )
          as _i3.Stream<Map<String, dynamic>?>);

  @override
  _i3.Stream<List<_i10.ChatMessage>> getMessages(String? chatId) =>
      (super.noSuchMethod(
            Invocation.method(#getMessages, [chatId]),
            returnValue: _i3.Stream<List<_i10.ChatMessage>>.empty(),
          )
          as _i3.Stream<List<_i10.ChatMessage>>);

  @override
  _i3.Future<List<_i10.ChatMessage>> getMessageHistory(
    String? chatId, {
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMessageHistory, [chatId], {#limit: limit}),
            returnValue: _i3.Future<List<_i10.ChatMessage>>.value(
              <_i10.ChatMessage>[],
            ),
          )
          as _i3.Future<List<_i10.ChatMessage>>);

  @override
  _i3.Future<void> deleteChat(String? chatId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteChat, [chatId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> wipeAllData() =>
      (super.noSuchMethod(
            Invocation.method(#wipeAllData, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
