// Mocks generated by Mockito 5.4.6 from annotations
// in soulmate/test/unit/user_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:firebase_auth/firebase_auth.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:soulmate/domain/entities/user.dart' as _i5;
import 'package:soulmate/domain/repositories/auth_repository.dart' as _i7;
import 'package:soulmate/domain/repositories/chat_repository.dart' as _i3;
import 'package:soulmate/domain/repositories/user_repository.dart' as _i2;
import 'package:soulmate/domain/usecases/delete_chat_usecase.dart' as _i11;
import 'package:soulmate/domain/usecases/get_active_chats_usecase.dart' as _i10;
import 'package:soulmate/domain/usecases/get_chat_id_usecase.dart' as _i12;
import 'package:soulmate/domain/usecases/get_current_user_usecase.dart' as _i16;
import 'package:soulmate/domain/usecases/get_users_usecase.dart' as _i9;
import 'package:soulmate/domain/usecases/save_feedback_usecase.dart' as _i13;
import 'package:soulmate/domain/usecases/update_user_field_usecase.dart'
    as _i15;
import 'package:soulmate/domain/usecases/upload_profile_image_usecase.dart'
    as _i14;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUserRepository_0 extends _i1.SmartFake
    implements _i2.UserRepository {
  _FakeUserRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeChatRepository_1 extends _i1.SmartFake
    implements _i3.ChatRepository {
  _FakeChatRepository_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i2.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> saveUser(_i5.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#saveUser, [user]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i5.User?> getUser(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getUser, [uid]),
            returnValue: _i4.Future<_i5.User?>.value(),
          )
          as _i4.Future<_i5.User?>);

  @override
  _i4.Future<List<_i5.User>> getUsers({
    String? gender,
    String? currentUserId,
    int? limit = 10,
    bool? refresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getUsers, [], {
              #gender: gender,
              #currentUserId: currentUserId,
              #limit: limit,
              #refresh: refresh,
            }),
            returnValue: _i4.Future<List<_i5.User>>.value(<_i5.User>[]),
          )
          as _i4.Future<List<_i5.User>>);

  @override
  _i4.Future<void> updateUserField(String? uid, Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserField, [uid, data]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> saveFeedback(String? userId, String? message) =>
      (super.noSuchMethod(
            Invocation.method(#saveFeedback, [userId, message]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String> uploadProfileImage(
    String? userId,
    dynamic imageFile, {
    String? userName,
    String? email,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #uploadProfileImage,
              [userId, imageFile],
              {#userName: userName, #email: email},
            ),
            returnValue: _i4.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(
                  #uploadProfileImage,
                  [userId, imageFile],
                  {#userName: userName, #email: email},
                ),
              ),
            ),
          )
          as _i4.Future<String>);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i7.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i8.User?> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i4.Stream<_i8.User?>.empty(),
          )
          as _i4.Stream<_i8.User?>);

  @override
  _i4.Future<_i8.UserCredential?> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i4.Future<_i8.UserCredential?>.value(),
          )
          as _i4.Future<_i8.UserCredential?>);

  @override
  _i4.Future<_i8.UserCredential?> signInWithApple() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithApple, []),
            returnValue: _i4.Future<_i8.UserCredential?>.value(),
          )
          as _i4.Future<_i8.UserCredential?>);

  @override
  _i4.Future<_i8.UserCredential?> signInWithEmailAndPassword(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmailAndPassword, [email, password]),
            returnValue: _i4.Future<_i8.UserCredential?>.value(),
          )
          as _i4.Future<_i8.UserCredential?>);

  @override
  _i4.Future<_i8.UserCredential?> registerWithEmailAndPassword(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#registerWithEmailAndPassword, [email, password]),
            returnValue: _i4.Future<_i8.UserCredential?>.value(),
          )
          as _i4.Future<_i8.UserCredential?>);

  @override
  _i4.Future<void> sendPasswordResetEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#sendPasswordResetEmail, [email]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> confirmPasswordReset({
    required String? code,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#confirmPasswordReset, [], {
              #code: code,
              #newPassword: newPassword,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateEmail(String? newEmail) =>
      (super.noSuchMethod(
            Invocation.method(#updateEmail, [newEmail]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updatePassword(String? newPassword) =>
      (super.noSuchMethod(
            Invocation.method(#updatePassword, [newPassword]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteAccount() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [GetUsersUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetUsersUseCase extends _i1.Mock implements _i9.GetUsersUseCase {
  MockGetUsersUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.UserRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeUserRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.UserRepository);

  @override
  _i4.Future<List<_i5.User>> call({
    String? gender,
    String? currentUserId,
    int? limit = 10,
    bool? refresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #gender: gender,
              #currentUserId: currentUserId,
              #limit: limit,
              #refresh: refresh,
            }),
            returnValue: _i4.Future<List<_i5.User>>.value(<_i5.User>[]),
          )
          as _i4.Future<List<_i5.User>>);
}

/// A class which mocks [GetActiveChatsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetActiveChatsUseCase extends _i1.Mock
    implements _i10.GetActiveChatsUseCase {
  MockGetActiveChatsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.ChatRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeChatRepository_1(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.ChatRepository);

  @override
  _i4.Future<List<Map<String, dynamic>>> call(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [userId]),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [DeleteChatUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteChatUseCase extends _i1.Mock implements _i11.DeleteChatUseCase {
  MockDeleteChatUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.ChatRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeChatRepository_1(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.ChatRepository);

  @override
  _i4.Future<void> call(String? chatId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [chatId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [GetChatIdUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetChatIdUseCase extends _i1.Mock implements _i12.GetChatIdUseCase {
  MockGetChatIdUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.ChatRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeChatRepository_1(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.ChatRepository);

  @override
  _i4.Future<String> call(String? userId1, String? userId2) =>
      (super.noSuchMethod(
            Invocation.method(#call, [userId1, userId2]),
            returnValue: _i4.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#call, [userId1, userId2]),
              ),
            ),
          )
          as _i4.Future<String>);
}

/// A class which mocks [SaveFeedbackUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveFeedbackUseCase extends _i1.Mock
    implements _i13.SaveFeedbackUseCase {
  MockSaveFeedbackUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.UserRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeUserRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.UserRepository);

  @override
  _i4.Future<void> call(String? userId, String? message) =>
      (super.noSuchMethod(
            Invocation.method(#call, [userId, message]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [UploadProfileImageUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUploadProfileImageUseCase extends _i1.Mock
    implements _i14.UploadProfileImageUseCase {
  MockUploadProfileImageUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.UserRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeUserRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.UserRepository);

  @override
  _i4.Future<String> call(
    String? userId,
    dynamic imageFile, {
    String? userName,
    String? email,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #call,
              [userId, imageFile],
              {#userName: userName, #email: email},
            ),
            returnValue: _i4.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(
                  #call,
                  [userId, imageFile],
                  {#userName: userName, #email: email},
                ),
              ),
            ),
          )
          as _i4.Future<String>);
}

/// A class which mocks [UpdateUserFieldUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateUserFieldUseCase extends _i1.Mock
    implements _i15.UpdateUserFieldUseCase {
  MockUpdateUserFieldUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.UserRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeUserRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.UserRepository);

  @override
  _i4.Future<void> call(String? uid, Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#call, [uid, data]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [GetCurrentUserUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCurrentUserUseCase extends _i1.Mock
    implements _i16.GetCurrentUserUseCase {
  MockGetCurrentUserUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.UserRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeUserRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.UserRepository);

  @override
  _i4.Future<_i5.User?> call(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#call, [uid]),
            returnValue: _i4.Future<_i5.User?>.value(),
          )
          as _i4.Future<_i5.User?>);
}
